### PR TITLE
Project: Social media website | Milestone: friendships v1

### PR DESCRIPTION
**Pull request by brenoxav**
> Project: Social media website

### Milestone 2: friendships v1

- Friendship feature
  - Add model + associations
  - Create model methods
  - Implement "Add friend" button with "add", "accept", "cancel" and "unfriend" functionalities

- Timeline
  - List only friend's posts
  - Show comments and likes count for each post

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
# Status: Invalid

**Hello team, I marked this pull request as invalid because there are no linter checks showing for this pull request. Please add the linter checks and send for another review.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Comment by brenoxav** [comment]
The GitHub Actions (linter checks) were activated.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @brenoxav :wave: 

You have really put in a lot of effort in this project by adding extra features like a cancel button for sent friend request and also adding more style to the webpage. Kudos 🥇 

However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  * [x] Your posts timeline currently does not show the current user's posts. Even when a friend request has been accepted, the timeline only contains posts from the accepted friend. Kindly fix that.
* [x] Add **Unit and Integration tests!** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @brenoxav  ! :wave:

#### You've done an amazing job in this project, I especially like the UI design and theme! Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
